import { betterAuth } from "better-auth";
import { mongodbAdapter } from "better-auth/adapters/mongodb";
import { genericOAuth } from "better-auth/plugins";

/** @type {ReturnType<import("better-auth").betterAuth> | null} */
let auth = null;

/**
 * Initialize the auth instance after the MongoDB connection is ready.
 * Must be called before getAuth() or mounting auth routes.
 * @param {import("mongodb").Db} db
 */
export function initAuth(db) {
  const serverUrl = process.env.SERVER_URL || "http://localhost:5050";
  const clientUrl = process.env.BETTER_AUTH_URL || "http://localhost:3000";

  const clientId = process.env.AUTH_CLIENT_ID;
  const clientSecret = process.env.AUTH_CLIENT_SECRET;
  const issuer = process.env.AUTH_ISSUER;
  const secret = process.env.BETTER_AUTH_SECRET;

  if (!clientId || !clientSecret || !issuer || !secret) {
    throw new Error(
      "Missing required auth environment variables. Check AUTH_CLIENT_ID, AUTH_CLIENT_SECRET, AUTH_ISSUER, and BETTER_AUTH_SECRET in config.env."
    );
  }

  auth = betterAuth({
    baseURL: serverUrl,
    trustedOrigins: [clientUrl],
    secret,
    database: mongodbAdapter(db),

    user: {
      // Expose isProfessor, firstName, lastName in the session so the frontend
      // can access them without a separate /users/:id call.
      additionalFields: {
        andrewId:    { type: "string",  required: false, defaultValue: "",    input: false },
        isProfessor: { type: "boolean", required: false, defaultValue: false, input: false },
        firstName:   { type: "string",  required: false, defaultValue: "",    input: false },
        lastName:    { type: "string",  required: false, defaultValue: "",    input: false },
        class:       { type: "string",  required: false, defaultValue: "",    input: false },
      },
    },

    databaseHooks: {
      user: {
        create: {
          before: async (user) => {
            // Keycloak LDAP maps uid → username, which is the Andrew ID directly.
            // Do NOT derive it from the email — users may have alias emails.
            const andrewId = /** @type {string} */ (user["username"] || user["preferred_username"] || "");

            // affiliations comes from eduPersonAffiliation (LDAP).
            // "faculty" indicates a professor; "staff" indicates staff.
            const affiliations = /** @type {string[]} */ (user["affiliations"] ?? []);
            const isProfessor =
              affiliations.includes("faculty") || affiliations.includes("staff");

            return {
              data: {
                ...user,
                // _id is auto-generated by better-auth; andrewId is stored separately.
                andrewId,

                // Read-only CMU directory fields from Keycloak LDAP
                firstName:   user["firstName"]   || user["given_name"]  || "",
                lastName:    user["lastName"]    || user["family_name"] || "",
                isProfessor,
                class:       user["class"]       || "",
                colleges:    user["colleges"]    || [],
                departments: user["departments"] || [],

                // User-editable app fields — start with defaults
                saved:       [],
                bio:         "",
                major:       "",
                interests:   [],
                experiences: [],
              },
            };
          },
        },
      },
    },

    plugins: [
      genericOAuth({
        config: [
          {
            providerId: "keycloak",
            clientId,
            clientSecret,
            discoveryUrl: `${issuer}/.well-known/openid-configuration`,
            redirectURI: `${serverUrl}/api/auth/oauth2/callback/keycloak`,
            scopes: ["openid", "email", "profile", "offline_access"],
          },
        ],
      }),
    ],
  });

  return auth;
}

export function getAuth() {
  if (!auth) throw new Error("Auth not initialized. Call initAuth(db) first.");
  return auth;
}
